widgets:
  todo:
    enabled: false
    colors:
      label: "green"
      text: "white"
    position:
      width: 20
      height: 5
  timer:
    enabled: true
    colors:
      label: "green"
      text: "white"
    position:
      width: 50
      height: 10
  spinner:
    enabled: false
    colors:
      label: "green"
      text: "white"
    position:
      width: 20
      height: 5
  table:
    enabled: true
    colors:
      label: "#ffffff"
      text: "#ffffff"
    position:
      width: 50
      height: 10
