widgets:
  todo:
    enabled: true
    colors:
      label: "green"
      text: "white"
    position:
      top: 1
      left: 2
      height: 1
      width: 1
  timer:
    enabled: true
    colors:
      label: "green"
      text: "white"
    position:
      top: 1
      left: 2
      height: 3
      width: 20